### ISSUE TITLE
CLI Notice issue

### ISSUE THREAD

**Issue by jenniferdou** [Skytells/Framework#1]
Hello,
I'm experiencing an issue during performing the following command 

> ./skytells init  

After performing the mentioned command, the following message appears above the command's outputs.

> Notice: Undefined index: help in Framework/Core/Kernel/Units/ConsoleKit/Seeds/Default.php on line 33

My SF version is 3.5,

Any help??

**Comment by Skytells** [comment]
Thanks for reporting the issue, 
During checking up your issue, we've found that the following notice'd thrown because of missing check-up function upon detecting the `init` command's options.

First of all, the issue has been reviewed and fixed and the fixes will be included with the next version.

At the time, please follow these steps to fix the issue on your current version of SF.

Open : 

```
/Core/Kernel/Units/ConsoleKit/Seeds/Default.php
```

At line (33)  Find : 

```php
if ($options["help"] == true){
```
Replace it with 

```php
if (isset($options["help"]) && $options["help"] == true){
```

Thanks,
Skytells, Inc.
